[target.'cfg(target_os = "linux")']
rustflags = ["-C", "link-args=-nostartfiles"]

[target.'cfg(target_os = "windows")']
rustflags = ["-C", "link-args=/ENTRY:_start /SUBSYSTEM:console"]

[target.'cfg(target_os = "macos")']
rustflags = ["-C", "link-args=-e __start -static -nostartfiles"]

# We need to recompile `core` for our original target
[unstable]
build-std = ["core", "compiler_builtins"]

# Set our own target to default
[build]
target = "x86_64-muos.json"
